//go:build integration

package turnstile_test

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/leodeim/captcher"
	"github.com/leodeim/captcher/turnstile"
)

// Cloudflare Turnstile test credentials (see Cloudflare's Turnstile testing docs).
const (
	// dummyToken is the token generated by Turnstile test sitekeys.
	dummyToken = "XXXX.DUMMY.TOKEN.XXXX"

	// secretAlwaysPass always passes validation.
	secretAlwaysPass = "1x0000000000000000000000000000000AA"

	// secretAlwaysFail always fails validation.
	secretAlwaysFail = "2x0000000000000000000000000000000AA"

	// secretTokenSpent returns a "timeout-or-duplicate" error.
	secretTokenSpent = "3x0000000000000000000000000000000AA"
)

func TestIntegration_Turnstile_Success(t *testing.T) {
	v := turnstile.New(secretAlwaysPass)

	resp, err := v.Verify(context.Background(), captcher.VerifyRequest{
		Token: dummyToken,
	})
	if err != nil {
		t.Fatalf("expected success, got error: %v", err)
	}
	if !resp.Success {
		t.Errorf("expected Success=true, got false; error codes: %v", resp.ErrorCodes)
	}
	if resp.Provider != captcher.ProviderTurnstile {
		t.Errorf("provider = %v, want %v", resp.Provider, captcher.ProviderTurnstile)
	}
	if resp.Hostname == "" {
		t.Error("expected non-empty hostname")
	}
	if resp.ChallengeTS.IsZero() {
		t.Error("expected non-zero ChallengeTS")
	}
}

func TestIntegration_Turnstile_Success_WithRemoteIP(t *testing.T) {
	v := turnstile.New(secretAlwaysPass)

	resp, err := v.Verify(context.Background(), captcher.VerifyRequest{
		Token:    dummyToken,
		RemoteIP: "203.0.113.50",
	})
	if err != nil {
		t.Fatalf("expected success, got error: %v", err)
	}
	if !resp.Success {
		t.Errorf("expected Success=true, got false; error codes: %v", resp.ErrorCodes)
	}
}

func TestIntegration_Turnstile_Failure(t *testing.T) {
	v := turnstile.New(secretAlwaysFail)

	resp, err := v.Verify(context.Background(), captcher.VerifyRequest{
		Token: dummyToken,
	})
	if err == nil {
		t.Fatal("expected error, got nil")
	}
	if !errors.Is(err, captcher.ErrVerifyFailed) {
		t.Errorf("expected ErrVerifyFailed, got: %v", err)
	}
	if resp == nil {
		t.Fatal("expected response even on failure")
	}
	if resp.Success {
		t.Error("expected Success=false")
	}
	if len(resp.ErrorCodes) == 0 {
		t.Error("expected non-empty error codes on failure")
	}
}

func TestIntegration_Turnstile_TokenAlreadySpent(t *testing.T) {
	v := turnstile.New(secretTokenSpent)

	resp, err := v.Verify(context.Background(), captcher.VerifyRequest{
		Token: dummyToken,
	})
	if err == nil {
		t.Fatal("expected error for token-already-spent, got nil")
	}
	if !errors.Is(err, captcher.ErrVerifyFailed) {
		t.Errorf("expected ErrVerifyFailed, got: %v", err)
	}
	if resp == nil {
		t.Fatal("expected response even on failure")
	}
	if resp.Success {
		t.Error("expected Success=false")
	}

	// Should contain "timeout-or-duplicate" error code.
	found := false
	for _, code := range resp.ErrorCodes {
		if code == "timeout-or-duplicate" {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("expected 'timeout-or-duplicate' in error codes, got: %v", resp.ErrorCodes)
	}
}

func TestIntegration_Turnstile_EmptyToken(t *testing.T) {
	v := turnstile.New(secretAlwaysPass)

	_, err := v.Verify(context.Background(), captcher.VerifyRequest{
		Token: "",
	})
	if !errors.Is(err, captcher.ErrMissingToken) {
		t.Errorf("expected ErrMissingToken, got: %v", err)
	}
}

func TestIntegration_Turnstile_AlwaysPassAcceptsAnyToken(t *testing.T) {
	// The always-pass secret accepts any token, validating Cloudflare's documented test behavior.
	v := turnstile.New(secretAlwaysPass)

	resp, err := v.Verify(context.Background(), captcher.VerifyRequest{
		Token: "any-arbitrary-token-value",
	})
	if err != nil {
		t.Fatalf("always-pass secret should accept any token, got error: %v", err)
	}
	if !resp.Success {
		t.Errorf("expected Success=true for always-pass secret; error codes: %v", resp.ErrorCodes)
	}
}

func TestIntegration_Turnstile_FailSecretRejectsAnyToken(t *testing.T) {
	// The always-fail test secret rejects all tokens, including the dummy one.
	v := turnstile.New(secretAlwaysFail)

	resp, err := v.Verify(context.Background(), captcher.VerifyRequest{
		Token: "any-arbitrary-token-value",
	})
	if err == nil {
		t.Fatal("expected error for always-fail secret, got nil")
	}
	if !errors.Is(err, captcher.ErrVerifyFailed) {
		t.Errorf("expected ErrVerifyFailed, got: %v", err)
	}
	if resp != nil && resp.Success {
		t.Error("expected Success=false for always-fail secret")
	}
}

func TestIntegration_Turnstile_InvalidSecret(t *testing.T) {
	v := turnstile.New("not-a-real-secret-key")

	resp, err := v.Verify(context.Background(), captcher.VerifyRequest{
		Token: dummyToken,
	})
	if err == nil {
		t.Fatal("expected error for invalid secret, got nil")
	}
	if resp != nil && resp.Success {
		t.Error("expected Success=false for invalid secret")
	}
}

func TestIntegration_Turnstile_ContextTimeout(t *testing.T) {
	v := turnstile.New(secretAlwaysPass, captcher.WithTimeout(1*time.Nanosecond))

	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Nanosecond)
	defer cancel()
	// Give the context time to expire.
	time.Sleep(5 * time.Millisecond)

	_, err := v.Verify(ctx, captcher.VerifyRequest{
		Token: dummyToken,
	})
	if err == nil {
		t.Fatal("expected timeout error, got nil")
	}
}

func TestIntegration_Turnstile_ResponseFields(t *testing.T) {
	v := turnstile.New(secretAlwaysPass)

	resp, err := v.Verify(context.Background(), captcher.VerifyRequest{
		Token: dummyToken,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Verify all response fields are populated as documented by Cloudflare.
	if !resp.Success {
		t.Error("expected Success=true")
	}
	if resp.Hostname == "" {
		t.Error("expected non-empty Hostname")
	}
	if resp.ChallengeTS.IsZero() {
		t.Error("expected non-zero ChallengeTS")
	}
	if resp.Provider != captcher.ProviderTurnstile {
		t.Errorf("provider = %v, want %v", resp.Provider, captcher.ProviderTurnstile)
	}
	// Cloudflare test responses include action="test" and cdata="test-data" (per docs; not hard-asserted).
	t.Logf("Response fields: Hostname=%q, Action=%q, CData=%q, ChallengeTS=%v",
		resp.Hostname, resp.Action, resp.CData, resp.ChallengeTS)
}
